name = "cors"
main = "src/index.ts"
compatibility_date = "2022-11-24"

kv_namespaces = [
    { binding = "ANALYTICS", id = "27584aa8ec83425483b92f6906e312c8", preview_id = "4daadfc8c22742acab5fb924892f76a9" },
]
